# docker-compose -f ./examples/sqlite/docker-compose.yml -p ags_mysql up
version: '3'
services:
    server:
        build: ../..
        depends_on:
            - database
        ports:
            - '3002:3001'
        volumes:
            - data:/app/data
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 60s
        container_name: ags_mysql_server
    database:
        image: 'mysql'
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: agspassword
            MYSQL_USER: agsuser
            MYSQL_PASSWORD: agspassword
            MYSQL_DATABASE: agsdb
        ports:
            - '3306:3306'
        volumes:
            - mysql:/var/lib/mysql
        container_name: ags_mysql_database
volumes:
    data:
    mysql:
